def croix():
    print("   \\      /")
    print("    \\    /")
    print("     \\  /")
    print("      \\/")
    print("      /\\")
    print("     /  \\")
    print("    /    \\")
    print("   /      \\")

def thick():
    print("             /")
    print("            /")
    print("           /")
    print("          /")
    print("         /")
    print("   \\    /")
    print("    \\  /")
    print("     \\/")

def pendu_haut_et_court():
    print("  ____________")
    print("  |      |")
    print("  |     / \\ - ARGHH !")
    print("  |     \\ /")
    print("  |    \\ | /")
    print("  |     \\|/")
    print("  |      |")
    print("  |      |")
    print("  |     / \\")
    print("  |    /   \\")
    print("  |")
    print(" / \\")
    print(" ---")
    
def pendaison_en_cours_veuillez_patienter(coups):
    if coups == 9:
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 8:
        print("  ____________")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 7:
        print("  ____________")
        print("  |      |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 6:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 5:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |      |")
        print("  |      |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 4:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |    \\ |")
        print("  |     \\|")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 3:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |    \\ | /")
        print("  |     \\|/")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 2:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |    \\ | /")
        print("  |     \\|/")
        print("  |      |")
        print("  |      |")
        print("  |")
        print("  |")
        print("  |")
        print(" / \\")
        print(" ---")
    if coups == 1:
        print("  ____________")
        print("  |      |")
        print("  |     / \\")
        print("  |     \\ /")
        print("  |    \\ | /")
        print("  |     \\|/")
        print("  |      |")
        print("  |      |")
        print("  |     / ")
        print("  |    /")
        print("  |")
        print(" / \\")
        print(" ---")
