def croix():
    print("   \\      /")
    print("    \\    /")
    print("     \\  /")
    print("      \\/")
    print("      /\\")
    print("     /  \\")
    print("    /    \\")
    print("   /      \\")

def thick():
    print("             /")
    print("            /")
    print("           /")
    print("          /")
    print("         /")
    print("   \\    /")
    print("    \\  /")
    print("     \\/")
 
def pendu_haut_et_court():
    print("  ____________")
    print("  |      |")
    print("  |     / \\ - ARGHH !")
    print("  |     \\ /")
    print("  |    \\ | /")
    print("  |     \\|/")
    print("  |      |")
    print("  |      |")
    print("  |     / \\")
    print("  |    /   \\")
    print("  |")
    print(" / \\")
    print(" ---")